### ISSUE TITLE
find stub error when packing

### ISSUE THREAD

**Issue by own2pwn** [93aef0ce4dd141ece6f5/Packer#1]
> 1st i've built packer stub

![1st](https://cloud.githubusercontent.com/assets/7850039/17651683/e0cb379e-6274-11e6-90f5-afeabf8df903.PNG)

>  next i've build packer with stub in same dir

![2nd](https://cloud.githubusercontent.com/assets/7850039/17651698/2d7dc264-6275-11e6-95fc-1c4cc7101a42.PNG)

> next i'm trying to pack exe
> but got error

![3](https://cloud.githubusercontent.com/assets/7850039/17651701/3da065de-6275-11e6-83ec-16f4db73cee8.PNG)
When i compile with VS i have virtualAlloc error 6, with mingw i cant link zlib lib

**Comment by 93aef0ce4dd141ece6f5** [comment]
zLib replaced with QuickLZ
